export interface VocabularyItem {
  word: string;
  emoji: string;
  image?: string;
  video?: string;
}

export interface SpyObject {
  name: string;
  x: number;
  y: number;
}

export interface LetterInfo {
  name: string;
  pronunciation: string;
  link?: string;
}

export interface LetterData {
  name: string;
  pronunciation: string;
  vocab: VocabularyItem[];
  shapes?: string[];
  spyObjects?: SpyObject[];
  folderName?: string;
}

export interface LetterSquare {
  letter: string;
  isTarget: boolean;
  hasDroppedCircle?: boolean;
}

export interface MatchingWord {
  word: string;
  wordIndex: number;
  isMatched?: boolean;
}

export interface GestureBox {
  letter: string;
  wordIndex: number;
  letterIndex: number;
  isMatched?: boolean;
}

export interface Vowel {
  symbol: string;
  name: string;
}

export interface SyllablePair {
  letter: string;
  vowel: string;
}

export type PageType =
  | 'introduction'
  | 'vocabulary'
  | 'writing'
  | 'letter-recognition'
  | 'syllable-writing'
  | 'vowel-writing'
  | 'matching';

/**
 * Per-page type for the manifest-driven 6-page numbers system.
 * Each number (0..10) has 6 worksheet pages of one of these types.
 */
export type NumberPageType =
  | 'learn'
  | 'write'
  | 'countChoose'
  | 'circleFind'
  | 'trace'
  | 'color';

/**
 * Numerals drawn on a countChoose / circleFind page. Coordinates are
 * percentages of the page image so they scale with whatever the page
 * is rendered at. `correct: true` means the numeral equals the number
 * being taught; `false` means it is a decoy / wrong answer.
 */
export interface NumberNumeral {
  value: number;
  xPct: number;
  yPct: number;
  wPct: number;
  hPct: number;
  correct: boolean;
}

/**
 * One worksheet page keyed by string "1".."6". The `image` field is
 * already an absolute path under /numbers/, computed from
 * `image` in the manifest.
 */
export interface NumberPageData {
  type: NumberPageType;
  image: string;
  numerals?: NumberNumeral[];
}

/**
 * Data for a single number 0..10. The 6-page system is keyed
 * `pages[k]` for k in `["1","2","3","4","5","6"]`. `word` is the
 * Arabic name (unvocalized, generated by `arabicWord(n)` so the
 * generator tests stay green). `videoUrl` is the trimmed mp4 used
 * on the `learn` page.
 */
export interface NumberData {
  value: number;
  word: string;
  videoUrl?: string;
  pages: Record<string, NumberPageData>;
}

export interface VideoPopupProps {
  isOpen: boolean;
  onClose: () => void;
  videoUrl?: string;
  word?: string;
  isLocal?: boolean;
}
